/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UNED.ControlCotizaciones.UI;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabián
 */
public class ActualizarCliente extends javax.swing.JFrame {

    /** Creates new form ActualizarCliente */
    public ActualizarCliente() {
        initComponents();
        this.setTitle("Actualizar cliente");
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblIdentificacion = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtBusquedaId = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        lblApellido2 = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblIngreso = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtIngreso = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 102, 153));
        lblTitulo.setText("Actualizar información");

        lblSubtitulo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSubtitulo.setText("Por favor, ingrese la identificación.");

        lblIdentificacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIdentificacion.setText("Identificación");

        btnBuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtBusquedaId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblCedula.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCedula.setText("Identificación");

        lblNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNombre.setText("Nombre");

        lblApellido1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblApellido1.setText("Primer apellido");

        lblApellido2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblApellido2.setText("Segundo apellido");

        lblEdad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEdad.setText("Edad");

        lblIngreso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIngreso.setText("Ingreso mensual");

        txtIdentificacion.setEditable(false);
        txtIdentificacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtApellido1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtApellido2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtEdad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtIngreso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UNED/ControlCotizaciones/Imagenes/actualizar_cliente.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblApellido2)
                                    .addComponent(lblEdad))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSubtitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(55, 55, 55)
                                    .addComponent(lblImagen))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnGuardar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnCancelar)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblIdentificacion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtBusquedaId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBuscar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblIngreso)
                                            .addGap(21, 21, 21)
                                            .addComponent(txtIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblCedula)
                                                .addComponent(lblNombre)
                                                .addComponent(lblApellido1))
                                            .addGap(31, 31, 31)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtNombre)
                                                .addComponent(txtApellido1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                                .addComponent(txtIdentificacion))))
                                    .addGap(43, 43, 43))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSubtitulo))
                    .addComponent(lblImagen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificacion)
                    .addComponent(btnBuscar)
                    .addComponent(txtBusquedaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido1)
                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido2)
                    .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngreso)
                    .addComponent(txtIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /* La imagen de para este JFrame, fue tomada de 
    https://pixabay.com/es/vectors/icono-iconos-mate-actualizar-1294539/
    
    La propiedad EXIT_ON_CLOSE de ActualizarCliente fue sustituida por DISPOSE, con
    el fin de mejorar el funcionamiento del programa.
    https://www.lawebdelprogramador.com/foros/Java/584264-cerrar-JFrame.html
    */
    
    // Método con la funcionalidad del botón Cancelar.
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false); // Oculta el JFrame ActualizarCliente.
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    // Método para la funcionalidad del botón Buscar.
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarDatosCliente();
    }//GEN-LAST:event_btnBuscarActionPerformed
    
    // Método para las funcionalidades del botón Guardar.
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        actualizarDatosCliente();
        // Las siguientes líneas permiten "limpiar" los campos del formulario.
        this.txtIdentificacion.setText("");
        this.txtBusquedaId.setText("");
        this.txtNombre.setText("");
        this.txtApellido1.setText("");
        this.txtApellido2.setText("");
        this.txtEdad.setText("");
        this.txtIngreso.setText("");
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    // Método para realizar la lectura del archivo clientes_prestamos.dat y mostrar la información del cliente.
    public void buscarDatosCliente() {
        FileReader leer = null;
        BufferedReader cargar = null;
        
        try {
            leer = new FileReader("C:\\Users\\monge\\Documents\\NetBeansProjects\\ControlCotizaciones\\clientes_prestamos.dat");
            cargar = new BufferedReader(leer);
            
            String cedula = this.txtBusquedaId.getText();
            String linea = "";
            
            List<String> datos = new ArrayList<>();
            
            while ((linea=cargar.readLine()) != null) {
                datos.add(linea);
            }
                        
            int indice = 0;
            if (datos.contains(cedula)) {
                indice = datos.indexOf(cedula);
                /* Al obtener la posición del elemento cédula en el ArrayList
                datos, se envía la información del cliente a cada campo del
                formulario según el índice inicial más la cantidad de espacios
                que es necesario ubicar para obtener dicha información.
                */
                this.txtIdentificacion.setText(datos.get(indice));
                this.txtNombre.setText(datos.get(indice + 1));
                this.txtApellido1.setText(datos.get(indice + 2));
                this.txtApellido2.setText(datos.get(indice + 3));
                this.txtEdad.setText(datos.get(indice + 4));
                this.txtIngreso.setText(datos.get(indice + 5));
            } else {
                JOptionPane.showMessageDialog(null, "Identificación no registrada.");
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error.");
        }
        finally {
            if (leer != null) {
                try {
                    leer.close();
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "No se pudo cerrar el archivo.");
                }
            }
        }
    }
    
    // Método para realizar la lectura del archivo clientes_prestamos.dat y realizar los cambios en el mismo.
    public void actualizarDatosCliente() {
        File archivo = null;
        File nuevoArchivo = null;
        FileReader leer = null;
        BufferedReader cargar = null;
        FileWriter escribirArchivo = null;
        PrintWriter escribir = null;
        
        try {
            archivo = new File("C:\\Users\\monge\\Documents\\NetBeansProjects\\ControlCotizaciones\\clientes_prestamos.dat");
            leer = new FileReader(archivo);
            cargar = new BufferedReader(leer);
            
            String cedula = this.txtBusquedaId.getText();
            String linea = "";
            
            List<String> datos = new ArrayList<>();
            
            while ((linea=cargar.readLine()) != null) {
                datos.add(linea);
            }
                        
            int indice = 0;
            if (datos.contains(cedula)) {
                indice = datos.indexOf(cedula);
                
                /* Para modificar la información que se encuentra almacenada en
                el ArrayList, se utilizó el método set(). Este método permite
                reemplazar la información almacenada en una posición específica 
                del ArrayList.
                https://lineadecodigo.com/java/reemplazar-un-elemento-del-arraylist/
                */
                datos.set(indice, this.txtIdentificacion.getText());
                datos.set(indice + 1, this.txtNombre.getText());
                datos.set(indice + 2, this.txtApellido1.getText());
                datos.set(indice + 3, this.txtApellido2.getText());
                datos.set(indice + 4, this.txtEdad.getText());
                datos.set(indice + 5, this.txtIngreso.getText());
                
                /* Para actualizar los datos del archivo, se empleó el método
                close(), ya que es necesario cerrarlo por el proceso FileReader,
                el cual está utilizando el archivo y esto impide eliminar el
                archivo "original".
                https://es.stackoverflow.com/questions/39503/borrar-fichero-en-java/219941 
                */
                leer.close();
                archivo.delete(); // Elimina el archivo inicial.
                // Se crea un nuevo archivo en el que se guardarán los datos del ArrayList ya modificacdos.
                nuevoArchivo = new File("C:\\Users\\monge\\Documents\\NetBeansProjects\\ControlCotizaciones\\clientes_prestamos.dat");
                escribirArchivo = new FileWriter("C:\\Users\\monge\\Documents\\NetBeansProjects\\ControlCotizaciones\\clientes_prestamos.dat", true);
                escribir = new PrintWriter(escribirArchivo);
                
                for (int i = 0; i < datos.size(); i++) { // El ciclo for iterará según el tamaño del ArrayList datos...
                    //Variable "temp" para guardar los datos según cada i del ArrayList "datos".
                    String temp = datos.get(i); // Se obtiene cada elemento de datos según el indice i de la iteración...
                    escribir.println(temp); // Para ser guadado en el archivo clientes_prestamos.dat.
                }
                JOptionPane.showMessageDialog(null, "¡Datos actualizados exitosamente!");
            } else {
                JOptionPane.showMessageDialog(null, "Identificación no registrada.");
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error en el programa.");
        }
        finally {
            if (archivo != null) {
                try {
                    leer.close();
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "No se pudo cerrar el archivo.");
                }
            }
            if (nuevoArchivo != null) {
                try {
                    leer.close();
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "No se pudo cerrar el archivo.");
                }
            }
            if (nuevoArchivo != null) {
                try {
                    escribirArchivo.close();
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "No se pudo cerrar el archivo.");
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblIngreso;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtBusquedaId;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtIngreso;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
