/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UNED.ControlCotizaciones.UI;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabián
 */
public class BorrarCliente extends javax.swing.JFrame {

    /**
     * Creates new form BorrarCliente
     */
    public BorrarCliente() {
        initComponents();
        this.setTitle("Eliminar cliente");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblIdentificación = new javax.swing.JLabel();
        txtBusquedaId = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCliente = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 102, 153));
        lblTitulo.setText("Eliminar la información de un cliente");

        lblSubtitulo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSubtitulo.setText("Por favor, ingrese la identificación.");

        lblIdentificación.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIdentificación.setText("Identificación");

        txtBusquedaId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UNED/ControlCotizaciones/Imagenes/eliminar_cliente.png"))); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtCliente.setEditable(false);
        txtCliente.setColumns(20);
        txtCliente.setRows(5);
        jScrollPane1.setViewportView(txtCliente);

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo)
                            .addComponent(lblSubtitulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(lblImagen))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIdentificación)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBusquedaId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSubtitulo))
                    .addComponent(lblImagen))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdentificación)
                            .addComponent(txtBusquedaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnEliminar))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /* La imagen de para este JFrame, fue tomada de 
    https://pixabay.com/es/vectors/bote-de-basura-reciclar-reciclaje-98470/
    
    La propiedad EXIT_ON_CLOSE de BorrarCliente fue sustituida por DISPOSE, con
    el fin de mejorar el funcionamiento del programa.
    https://www.lawebdelprogramador.com/foros/Java/584264-cerrar-JFrame.html
    */
    
    // Método con la función del botón Cancelar.
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false); // Oculta el JFrame BorrarCliente.
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    // Método para la funcionalidad del botón Buscar.
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarDatosCliente();
    }//GEN-LAST:event_btnBuscarActionPerformed
    
    // Método para las funcionalidades del botón Eliminar.
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarDatosCliente();
        // Las siguientes líneas "limpian" los campos de texto.
        this.txtBusquedaId.setText("");
        this.txtCliente.setText("");
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    // Método que permite realizar la lectura del archivo clientes_presatmos.dat y mostrar su información.
    public void buscarDatosCliente() {
        FileReader leer = null;
        BufferedReader cargar = null;
        
        try {
            leer = new FileReader("C:\\Users\\monge\\Documents\\NetBeansProjects\\ControlCotizaciones\\clientes_prestamos.dat");
            cargar = new BufferedReader(leer);
            
            String cedula = this.txtBusquedaId.getText();
            String linea = "";
            
            List<String> datos = new ArrayList<>();
            
            while ((linea=cargar.readLine()) != null) {
                datos.add(linea);
            }
                        
            int indice = 0;
            if (datos.contains(cedula)) {
                indice = datos.indexOf(cedula);
                
                String id = datos.get(indice);
                String nombre = datos.get(indice + 1);
                String a1 = datos.get(indice + 2);
                String a2 = datos.get(indice + 3);
                String edad = datos.get(indice + 4);
                String ingreso = datos.get(indice + 5);
                
                this.txtCliente.setText("Identificación: " + id + "\n" +
                        "Nombre: " + nombre + "\n" +
                        "Primer apellido: " + a1 + "\n" +
                        "Segundo apellido: " + a2 + "\n" +
                        "Edad: " + edad + "\n" +
                        "Ingreso mensual: " + ingreso + "\n");
            } else {
                JOptionPane.showMessageDialog(null, "Identificación no registrada.");
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error.");
        }
        finally {
            if (leer != null) {
                try {
                    leer.close();
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "No se pudo cerrar el archivo.");
                }
            }
        }
    }
    
    /* Método que permite realizar la lectura de los archivos clientes_prestamos.dat 
    y prestamos_aprobados.dat, para eliminar a un cliente del primer archivo mencionado.
    */
    public void eliminarDatosCliente() {
        File archivo1 = null;
        File archivo2 = null;
        File nuevoArchivo = null;
        FileReader leer1 = null;
        FileReader leer2 = null;
        BufferedReader cargar = null;
        FileWriter escribirArchivo = null;
        PrintWriter escribir = null;
        
        try {
            // Lectura del archivo clientes_prestamos.dat.
            archivo1 = new File("C:\\Users\\monge\\Documents\\NetBeansProjects\\ControlCotizaciones\\clientes_prestamos.dat");
            leer1 = new FileReader(archivo1);
            cargar = new BufferedReader(leer1);
            
            String cedula = this.txtBusquedaId.getText();
            String linea = "";
            
            List<String> datos1 = new ArrayList<>();
            
            while ((linea=cargar.readLine()) != null) {
                datos1.add(linea);
            }
            
            // Lectura del archivo prestamos_aprobados.dat.
            archivo2 = new File("C:\\Users\\monge\\Documents\\NetBeansProjects\\ControlCotizaciones\\prestamos_aprobados.dat");
            leer2 = new FileReader(archivo2);
            cargar = new BufferedReader(leer2);
            // ArrayList para almacenar los datos del archivo prestamos_aprobados.dat.
            List<String> datos2 = new ArrayList<>();
            
            while ((linea=cargar.readLine()) != null) {
                datos2.add(linea); // Ciclo para obtener cada dato del archivo prestamos_aprobados.dat.
            }
                        
            int indice = 0;
            if (datos2.contains(cedula)) { // Si el ArrayList datos2 (prestamos_aprobados.dat) contiene cedula...
                // No se permitirá eliminar el cliente, ya que se deduce que este posee préstamos aprobados.
                JOptionPane.showMessageDialog(null, "No se puede eliminar." +
                        "\n" + "El cliente posee préstamos aprobados.");
            } else { // Sin embargo, de ser lo contrario...
                // Obtenemos el índice de cedula en el ArrayList datos1 (prestamos_clientes.dat)...
                indice = datos1.indexOf(cedula);
                /* Y se realiza una iteración con el fin de eliminar los elementos
                correspondientes a la información del cliente. En cada iteración,
                indice es removido del ArrayList datos1 hasta finalizar el ciclo
                de iteración. En este caso, cada elemento correspondiente a los
                datos del cliente toma la posición de indice al ser eliminado.
                */
                for (int i = 0; i < 6; i++) { 
                    datos1.remove(indice);
                }
                
                /* Para actualizar los datos del archivo, se empleó el método
                close(), ya que es necesario cerrar el proceso FileReader,
                el cual está utilizando el archivo y esto impide eliminar el
                archivo "original".
                https://es.stackoverflow.com/questions/39503/borrar-fichero-en-java/219941 
                */
                leer1.close();
                archivo1.delete(); // Se elimina el archivo inicial.
                // Se crea un nuevo archivo donde se ingresarán los elementos del ArrayList datos1 ya eliminados.
                nuevoArchivo = new File("C:\\Users\\monge\\Documents\\NetBeansProjects\\ControlCotizaciones\\clientes_prestamos.dat");
                escribirArchivo = new FileWriter("C:\\Users\\monge\\Documents\\NetBeansProjects\\ControlCotizaciones\\clientes_prestamos.dat", true);
                escribir = new PrintWriter(escribirArchivo);
                
                for (int i = 0; i < datos1.size(); i++) {
                    //Variable "temp" para guardar los datos según cada posición del ArrayList "datos".
                    String temp = datos1.get(i);
                    escribir.println(temp);
                }
                JOptionPane.showMessageDialog(null, "¡Eliminación exitosa!");
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error en el programa.");
        }
        finally {
            if (archivo1 != null) {
                try {
                    leer1.close();
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "No se pudo cerrar el archivo.");
                }
            }
            if (archivo2 != null) {
                try {
                    leer2.close();
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "No se pudo cerrar el archivo.");
                }
            }
            if (nuevoArchivo != null) {
                try {
                    escribirArchivo.close();
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "No se pudo cerrar el archivo.");
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdentificación;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtBusquedaId;
    private javax.swing.JTextArea txtCliente;
    // End of variables declaration//GEN-END:variables
}
